name: Dev Build on Commit

#  Trigger on every push (all branches), you can scope this to a branch
on:
  push:
    branches: [ '**' ]

jobs:
  dev-build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Check out code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Java (required by Gradle) & Android SDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Install Ruby (for Fastlane) and dependencies
      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Bundler & Gems
        run: |
          gem install bundler
          bundle install

      # 4️⃣ Install Node.js & Firebase CLI (if you distribute via CLI)
      - name: Install Node.js and Firebase CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # 5️⃣ Export necessary secrets into environment
      #    — Set these in your GitHub repo’s Settings → Secrets:
      #      * FIREBASE_TOKEN
      #      * FIREBASE_APP_ID_CF  (if using distribution)
      #      * FIREBASE_CF_GROUP  (if using distribution)
      - name: Export Firebase credentials
        run: |
          echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID_CF=${{ secrets.FIREBASE_APP_ID_CF }}" >> $GITHUB_ENV
          echo "FIREBASE_CF_GROUP=${{ secrets.FIREBASE_CF_GROUP }}" >> $GITHUB_ENV

      # 6️⃣ Run the dev_build lane
      - name: Run Fastlane dev_build
        working-directory: ${{ github.workspace }}
        run: |
          bundle exec fastlane dev_build
